#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-ant-tasks
Version  : 2.1.3
Release  : 1
URL      : https://github.com/apache/maven-ant-tasks/archive/maven-ant-tasks-2.1.3.tar.gz
Source0  : https://github.com/apache/maven-ant-tasks/archive/maven-ant-tasks-2.1.3.tar.gz
Source1  : http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
Source2  : http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-ant-tasks-data = %{version}-%{release}
BuildRequires : apache-ant
BuildRequires : buildreq-mvn

%description
Maven Ant Tasks
$Id$
Building the Ant Tasks
----------------------
The Maven Ant Tasks can be build with Maven 2.x (2.2.1 is recommended).  From the root directory run
"mvn install"

%package data
Summary: data components for the mvn-maven-ant-tasks package.
Group: Data

%description data
data components for the mvn-maven-ant-tasks package.


%prep
%setup -q -n maven-ant-tasks-maven-ant-tasks-2.1.3

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.pom
